sudo: required

language: node_js

node_js:
  - "5.5"

python:
  - "2.7"

before_install: 
  - sudo pip install flask
  - sudo pip install flask-socketio
  - sudo pip install esky
  - npm install -g bower
  - npm install -g polybuild
  - npm install shelljs@0.6.0


install:
  - bower install
  - node build.js

