sudo: required

language: node_js

node_js:
  - "5.5"

python:
  - "2.7"

# cache: pip

before_install:
  - sudo pip install flask
  - sudo pip install flask-socketio
  - sudo pip install esky
  - sudo pip install eventlet
  - sudo pip install py2exe
  - npm install -g bower
  - npm install -g polybuild
  - npm install -g vulcanize
  - npm install shelljs@0.6.0


install:
  - bower install
  - node build.js

notifications:
  email: false
