version: 1.0.{build}

environment:
  # nodejs_version: "0.12.7"
  matrix:
    # First group is 32 bit python 2.7
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

platform: x86

configuration: Release

cache:
  - static/bower_components
  - node_modules                    # local npm modules
  - '%APPDATA%\npm-cache'           # npm cache
  
init:
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, verify which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"

  # Ensure node x86 (appveyor powershell script to switch installed versions)
  - ps: Install-Product node 5.5.0 x86
  - cmd: node --version
  - cmd: npm --version

  # Set the relevant pip location to the path 
  - cmd: set PATH=%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%


install:
  - cmd: npm install -g bower
  - cmd: npm install -g polybuild
  - cmd: npm install -g vulcanize
  - cmd: npm install shelljs@0.6.0

  - cmd: bower install

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - cmd: pip install --disable-pip-version-check --user --upgrade pip

  # Install python dependencies
  # - cmd: pip install https://dl.dropboxusercontent.com/u/74034/ardublockly-dep/win/py2exe-0.6.10a1-cp27-none-win32.whl
  - cmd: pip install flask
  - cmd: pip install flask-socketio
  - cmd: pip install esky
  - cmd: pip install eventlet
  - cmd: pip install py2exe_py2
  - cmd: pip install cx-Freeze

  # - cmd: python -OO setup.py bdist_esky
  - cmd: node build.js

# Not a project with an msbuild file, build done at install.
build: off 

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*
  
