version: 1.0.{build}

environment:
  # nodejs_version: "0.12.7"
  matrix:
    # First group is 32 bit python 2.7
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

platform: x86

init:
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, verify which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"

  # Ensure node x86 (appveyor powershell script to switch installed versions)
  - ps: Install-Product node 5.1.0 x86
  - cmd: node --version
  - cmd: npm --version

  # Set the relevant pip location to the path 
  - cmd: set PATH=%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%


build_script:
- cmd: >-
    pip install flask
    
    pip install flask-socketio
    
    pip install esky
    
    pip install eventlet
    
    pip install py2exe

    python -OO setup.py bdist_esky
  
